/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'karen_ki' at '12/13/19 8:05 PM' with Gradle 2.10
 *
 * @author karen_ki, @date 12/13/19 8:05 PM
 */
package com.karen;
public class Library {
    public String getMessage() {
        return "Hi from lib";
    }
}
